### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by azimjonn** [AlibabaResearch/AdvancedLiterateMachinery#29]
I cannot run train.py.
`python train.py --config=configs/finetune_funsd.yaml

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from lightning_modules.data_modules.vie_data_module import VIEDataModule
  File "/home/me/projects/UzPostOCR/AdvancedLiterateMachinery/DocumentUnderstanding/GeoLayoutLM/lightning_modules/data_modules/vie_data_module.py", line 8, in <module>
    import cv2
  File "/home/me/miniconda3/envs/geo/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/me/miniconda3/envs/geo/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/me/miniconda3/envs/geo/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/me/miniconda3/envs/geo/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/me/miniconda3/envs/geo/lib/python3.8/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`

**Comment by ccx1997** [comment]
Try to install with the earlier version:
`pip install opencv-python==4.5.5.64`

**Comment by mohammadreza-sheykhmousa** [comment]
## Description

I encountered a segmentation fault while training a model using the `GeoLayoutLM` on a CUDA-enabled GPU. The error occurs after loading the training data and during the sanity check of the DataLoader. Below are the details of the environment and the error message.

## Environment

- **Operating System**: Linux-5.10.210-201.852.amzn2.x86_64-x86_64-with-glibc2.26
- **PyTorch Version**: 2.3.1+cu121
- **PyTorch Lightning Version**: 2.3.3
- **Transformers Version**: 4.42.3
- **CUDA Version**: Build
- **NVIDIA Driver Version**: 12.4
- **CUDA Available**: True
- **CUDA Device Count**: 1
- **CUDA Device Name**: NVIDIA A10G

## Error Message

Seed set to 1
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Trainer(limit_val_batches=1.0) was configured so 100% of the batches will be used..
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BertTokenizer'.
The class this function is called from is 'BrosTokenizer'.
/path/to/your/environment/lib/python3.11/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
[INFO] init weight from /path/to/your/model/weights/geolayoutlm_large_pretrain.pt
data_root: /path/to/your/dataset/funsd_geo
Number of examples loaded: 149
Elapsed time for loading training data: 0.16243743896484375
data_root: /path/to/your/dataset/funsd_geo
Number of examples loaded: 50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

| Name | Type | Params | Mode
0 | net | GeoLayoutLMVIEModel | 415 M | train
415 M Trainable params
0 Non-trainable params
415 M Total params
1,662.087 Total estimated model params size (MB)
Sanity Checking DataLoader 0: 0%| | 0/2 [00:00<?, ?it/s]/path/to/your/environment/lib/python3.11/site-packages/transformers/modeling_utils.py:1060: FutureWarning: The device argument is deprecated and will be removed in v5 of Transformers.
warnings.warn(
Segmentation fault


## Steps to Reproduce

1. Set up the environment with the specified versions of PyTorch, PyTorch Lightning, Transformers, and CUDA.
2. Initialize the `GeoLayoutLMVIEModule` and load the pre-trained weights.
3. Start the training process with the FUNSD dataset.
4. Observe the segmentation fault during the sanity check of the DataLoader.

## Additional Information

- I have ensured that my NVIDIA drivers and CUDA toolkit are up-to-date.
- The error suggests that there may be an issue with the handling of the `device` argument in the Transformers library.
- My goal is to reconstruct the fine-tuning process as described in the paper.

Please let me know if you need any additional information or logs to diagnose this issue. Any help or guidance would be greatly appreciated.
